#!/usr/bin/env python3
"""
Simple report generator that creates readable analysis reports
"""

from datetime import datetime
from typing import Dict, Any

def generate_readable_report(job: dict) -> str:
    """Generate a comprehensive, readable text report"""
    result = job["result"]
    
    # Prepare report data
    file_name = job["file_name"]
    analysis_date = datetime.fromtimestamp(job["created_at"]).strftime('%Y-%m-%d %H:%M:%S UTC')
    authentic_pct = result['authentic_percentage']
    deepfake_pct = result['deepfake_percentage']
    confidence = result['overall_confidence'] * 100
    processing_time = result['processing_time']
    model_version = result['model_version']
    
    # Determine recommendation
    if deepfake_pct > authentic_pct:
        recommendation = "⚠️ POTENTIAL DEEPFAKE DETECTED"
        risk_level = "HIGH RISK"
    else:
        recommendation = "✅ CONTENT APPEARS AUTHENTIC"
        risk_level = "LOW RISK"
    
    # Create comprehensive text report
    report = f"""
🛡️ DEEPFAKE DETECTION ANALYSIS REPORT
{'='*60}

📋 REPORT INFORMATION
{'-'*30}
File Name: {file_name}
Analysis Date: {analysis_date}
Job ID: {job['job_id']}
File Size: {job['file_size']:,} bytes
Processing Time: {processing_time:.1f} seconds
Model Version: {model_version}

🎯 DETECTION RESULTS
{'-'*30}
{recommendation}
Risk Level: {risk_level}
Overall Confidence: {confidence:.1f}%

📊 PERCENTAGE BREAKDOWN:
• Authentic Probability: {authentic_pct:.1f}%
• Deepfake Probability: {deepfake_pct:.1f}%

🔍 TECHNICAL ANALYSIS
{'-'*30}
Image Quality Score: {result['quality_metrics']['image_quality']*100:.1f}%
Face Detection Confidence: {result['quality_metrics']['face_detection_confidence']*100:.1f}%
Artifact Score: {result['quality_metrics']['artifact_score']:.3f}
Authentic Quality Score: {result['quality_metrics']['authentic_quality_score']:.3f}
Evidence Balance: {result['quality_metrics']['evidence_balance']:.3f}
Total Frames Analyzed: {result['analysis_metadata']['total_frames']}
Suspicious Patterns: {'Detected' if result['analysis_metadata']['suspicious_patterns_detected'] else 'None'}
Authentic Quality: {'High' if result['analysis_metadata']['authentic_quality_detected'] else 'Normal'}

📹 FRAME-BY-FRAME ANALYSIS
{'-'*30}
Detailed analysis of individual frames (showing first 10):

Frame# | Time  | Deepfake | Confidence | Regions | Artifacts
-------|-------|----------|------------|---------|----------"""

    # Add frame analysis
    for i, frame in enumerate(result['frame_scores'][:10]):
        artifacts = "Yes" if frame['artifacts_detected'] else "No"
        report += f"""
{frame['frame_index']+1:6d} | {frame['timestamp']:5.1f}s | {frame['deepfake_score']*100:7.1f}% | {frame['confidence']*100:9.1f}% | {frame['suspicious_regions']:7d} | {artifacts:9s}"""
    
    if len(result['frame_scores']) > 10:
        report += f"\n\n... and {len(result['frame_scores']) - 10} more frames analyzed"
    
    report += f"""

🔬 METHODOLOGY & TRAINING DATA
{'-'*30}
Training Dataset: {result['analysis_metadata']['training_dataset']}
Detection Algorithms: {', '.join(result['analysis_metadata']['detection_algorithms'])}
Model Accuracy: {result['analysis_metadata']['model_accuracy']}

DETECTION CAPABILITIES:
• Facial artifact detection and inconsistency analysis
• Temporal coherence verification in video content
• Lighting and shadow consistency evaluation
• Skin texture and facial feature analysis
• Boundary detection around manipulated regions

📝 RECOMMENDATIONS
{'-'*30}"""
    
    if deepfake_pct > authentic_pct:
        report += """
⚠️ CAUTION: Potential synthetic content detected
• Verify content through additional sources
• Consider the context and origin of this media
• Do not use for critical decision-making without verification
• Be aware of potential manipulation
• Cross-reference with original content if available"""
    else:
        report += """
✅ Content appears to be authentic
• However, no detection system is 100% accurate
• Always consider source and context
• Sophisticated deepfakes may evade detection
• Use additional verification methods when critical
• Stay updated with latest detection technologies"""
    
    report += f"""

⚖️ LEGAL & ETHICAL DISCLAIMER
{'-'*30}
This report is generated by an AI system for informational purposes only.
Results should not be used as sole evidence in legal proceedings.
The technology may produce false positives or false negatives.
Always verify results through multiple sources and methods.
Respect privacy and consent when analyzing media content.

📄 REPORT METADATA
{'-'*30}
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}
System: DeepFake Detection System v{model_version}
Report Format: Comprehensive Text Analysis
Total Analysis Time: {processing_time:.1f} seconds

{'='*60}
END OF REPORT
{'='*60}
    """
    
    return report